Global:
  debug: false
  use_gpu: true
  epoch_num: 700
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: ./output/vi_PP-OCR_V3_det_student_newdata_v1/
  save_epoch_step: 20
  eval_batch_step:
  - 0
  - 10
  cal_metric_during_train: false
  pretrained_model: /raid/kientdt/shared_drive_cv/ocr/kientdt/PaddleOCR2Pytorch/ch_ptocr_v3_det_infer_student.pth
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
  distributed: true

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: True
  Neck:
    name: RSEFPN
    out_channels: 96
    shortcut: True
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /raid/kientdt/shared_drive_cv/ocr/kientdt/DetectionData/images_ver1
    label_file_list:
      - /raid/kientdt/shared_drive_cv/ocr/kientdt/DetectionData/detection_train_ver1.txt
    ratio_list: [1.0] #ratio to sample data if there are many label_file_list
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    # - DetAug:
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 960
        - 960
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 64
    num_workers: 16
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /raid/kientdt/shared_drive_cv/ocr/kientdt/DetectionData/images_ver1
    label_file_list:
      - /raid/kientdt/shared_drive_cv/ocr/kientdt/DetectionData/detection_test_ver1.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    # - DetAug:
    - DetLabelEncode: null
    - DetResizeForTest: null
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 16
# Comment to infer: python3 tools/infer/predict_det.py --det_algorithm="DB" --det_model_dir="./inference/vi_det_db_inference/" --image_dir="/raid/kientdt/shared_drive_cv/ocr/kientdt/DetectionData/images/01_2004_CT-BXD/page_num_0_block_num_7.png" --use_gpu=True
# Export model: python3 tools/export_model.py -c configs/det/ch_PP-OCRv3/vi_PP-OCRv3_det_student_augmentation.yml -o Global.pretrained_model="./output/vi_PP-OCR_V3_det_augmentation/latest" Global.save_inference_dir="./inference/vi_det_db_inference_best_accuracy_with_augmentation/"